export const mockBooks = [
  {
    id: '1',
    title: 'Dom Casmurro',
    author: 'Machado de Assis',
    imageUrl: 'https://blog-cdn.reedsy.com/directories/gallery/248/large_65b0ae90317f7596d6f95bfdd6131398.jpg',
    rating: 4.5,
    readingTime: '12 min',
  },
  {
    id: '2',
    title: 'Grande Sertão: Veredas',
    author: 'João Guimarães Rosa',
    imageUrl: 'https://bukovero.com/wp-content/uploads/2016/07/Harry_Potter_and_the_Cursed_Child_Special_Rehearsal_Edition_Book_Cover.jpg',
    rating: 4.8,
    readingTime: '15 min',
  },
  {
    id: '3',
    title: 'O Cortiço',
    author: 'Aluísio Azevedo',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBNkUjnuFpNKpacq24GVqOjsei-eIjCKgMtA&s',
    rating: 4.2,
    readingTime: '10 min',
  },
  {
    id: '4',
    title: 'A Hora da Estrela',
    author: 'Clarice Lispector',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsfxrcUtlaLqSTTpA7N9cWKIopvRNtXngM2A&s',
    rating: 3.9,
    readingTime: '8 min',
  },
  {
    id: '5',
    title: 'Memórias Póstumas de Brás Cubas',
    author: 'Machado de Assis',
    imageUrl: 'https://marketplace.canva.com/EAFsdNksbxY/3/0/1003w/canva-black-and-white-minimalist-simple-modern-photography-collection-book-cover-Yo5zzlHVSpA.jpg',
    rating: 4.7,
    readingTime: '13 min',
  },
  {
    id: '6',
    title: 'Iracema',
    author: 'José de Alencar',
    imageUrl: 'https://miblart.com/wp-content/uploads/2024/01/main-6-scaled.jpg',
    rating: 3.5,
    readingTime: '9 min',
  },
  {
    id: '7',
    title: 'Vidas Secas',
    author: 'Graciliano Ramos',
    imageUrl: 'https://i.ebayimg.com/images/g/JRAAAOSwGihfalVv/s-l1200.jpg',
    rating: 4.3,
    readingTime: '11 min',
  },
  {
    id: '8',
    title: 'O Guarani',
    author: 'José de Alencar',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCpH6IsJJhtLgonP0w3brHbsoslJgNyrZXSw&s',
    rating: 3.8,
    readingTime: '7 min',
  },
];
